//THIS FILE IS GENERATED
#define CRTMPSERVER_VERSION_BUILD_DATE 1428173942
#define CRTMPSERVER_VERSION_BUILD_NUMBER "811"
#define CRTMPSERVER_VERSION_RELEASE_NUMBER "1.1_rc1"
#define CRTMPSERVER_VERSION_CODE_NAME "Gladiator"
#define CRTMPSERVER_VERSION_BUILDER_OS_NAME ""
#define CRTMPSERVER_VERSION_BUILDER_OS_VERSION ""
#define CRTMPSERVER_VERSION_BUILDER_OS_ARCH ""
#define CRTMPSERVER_VERSION_BUILDER_OS_UNAME "Linux raspberrypi 3.18.7+ #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015 armv6l GNU/Linux"
